# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pygo_plugin/proto/grpc_broker.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pygo_plugin/proto/grpc_broker.proto',
  package='plugin',
  syntax='proto3',
  serialized_options=b'Z\006plugin',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n#pygo_plugin/proto/grpc_broker.proto\x12\x06plugin\"@\n\x08\x43onnInfo\x12\x12\n\nservice_id\x18\x01 \x01(\r\x12\x0f\n\x07network\x18\x02 \x01(\t\x12\x0f\n\x07\x61\x64\x64ress\x18\x03 \x01(\t2C\n\nGRPCBroker\x12\x35\n\x0bStartStream\x12\x10.plugin.ConnInfo\x1a\x10.plugin.ConnInfo(\x01\x30\x01\x42\x08Z\x06pluginb\x06proto3'
)




_CONNINFO = _descriptor.Descriptor(
  name='ConnInfo',
  full_name='plugin.ConnInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='service_id', full_name='plugin.ConnInfo.service_id', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='network', full_name='plugin.ConnInfo.network', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='address', full_name='plugin.ConnInfo.address', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=47,
  serialized_end=111,
)

DESCRIPTOR.message_types_by_name['ConnInfo'] = _CONNINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ConnInfo = _reflection.GeneratedProtocolMessageType('ConnInfo', (_message.Message,), {
  'DESCRIPTOR' : _CONNINFO,
  '__module__' : 'pygo_plugin.proto.grpc_broker_pb2'
  # @@protoc_insertion_point(class_scope:plugin.ConnInfo)
  })
_sym_db.RegisterMessage(ConnInfo)


DESCRIPTOR._options = None

_GRPCBROKER = _descriptor.ServiceDescriptor(
  name='GRPCBroker',
  full_name='plugin.GRPCBroker',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=113,
  serialized_end=180,
  methods=[
  _descriptor.MethodDescriptor(
    name='StartStream',
    full_name='plugin.GRPCBroker.StartStream',
    index=0,
    containing_service=None,
    input_type=_CONNINFO,
    output_type=_CONNINFO,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_GRPCBROKER)

DESCRIPTOR.services_by_name['GRPCBroker'] = _GRPCBROKER

# @@protoc_insertion_point(module_scope)
