# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pygo_plugin/proto/grpc_controller.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pygo_plugin/proto/grpc_controller.proto',
  package='plugin',
  syntax='proto3',
  serialized_options=b'Z\006plugin',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\'pygo_plugin/proto/grpc_controller.proto\x12\x06plugin\"\x07\n\x05\x45mpty2:\n\x0eGRPCController\x12(\n\x08Shutdown\x12\r.plugin.Empty\x1a\r.plugin.EmptyB\x08Z\x06pluginb\x06proto3'
)




_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='plugin.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=51,
  serialized_end=58,
)

DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'pygo_plugin.proto.grpc_controller_pb2'
  # @@protoc_insertion_point(class_scope:plugin.Empty)
  })
_sym_db.RegisterMessage(Empty)


DESCRIPTOR._options = None

_GRPCCONTROLLER = _descriptor.ServiceDescriptor(
  name='GRPCController',
  full_name='plugin.GRPCController',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=60,
  serialized_end=118,
  methods=[
  _descriptor.MethodDescriptor(
    name='Shutdown',
    full_name='plugin.GRPCController.Shutdown',
    index=0,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_GRPCCONTROLLER)

DESCRIPTOR.services_by_name['GRPCController'] = _GRPCCONTROLLER

# @@protoc_insertion_point(module_scope)
