name: Build and test

# Run the jobs for pushes and pull requests targeting main branch.
on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Job which sets up the dependencies and builds the project.
  build:
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.11', '3.12']
        go-version: ['1.24.x']
    name: 'Build ${{ matrix.os }} <py=${{ matrix.python-version }}, go=${{ matrix.go-version }}>'
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: "Install go dependencies"
        run: |
          go install golang.org/x/tools/cmd/goimports@latest
          go install github.com/go-python/gopy@master
          echo "$(go env GOPATH)/bin" >> "$GITHUB_PATH"

      - name: "Install pygo-plugin"
        run: |
          sudo apt-get update && sudo apt-get install -y libpython3-dev
          pip install ".[test]"

      - name: "Run Tests"
        run: python -m pytest ./tests
