name: Build and test

# Run the jobs for pushes and pull requests targetting main branch.
on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Job which sets up the dependencies and builds the project.
  build:
    strategy:
      matrix:
        os: [ubuntu-18.04]
        python-version: [3.8]
        go-version: [1.15.x]
    name: 'Build ${{ matrix.os }} <py=${{ matrix.python-version }}, go=${{ matrix.go-version }}>'
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}

      - name: "Install go dependencies"
        run: |
          go get golang.org/x/tools/cmd/goimports
          go get github.com/go-python/gopy@master

      - name: "Install python dependencies"
        run: pip install -r requirements.txt

      - name: "Install pygo-plugin"
        run: python setup.py install

      - name: "Run Tests"
        run: python -m pytest ./tests
